
LocationPath: "/workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/location_solver.json"
ScenarioPath: "/workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/scenario_solver_6.json"
PlanPath: "/workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/scenario_6_plan_10.json"
Mode: "Standard" 
DebugLevel: 0


TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5

SimulatedAnnealing:
  MaxDuration: 180
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  IntensifyOnImprovement: false

DeepLook:
  TestCases: 0
  MaxTest: 100
  EvaluatorInput:
    Path: "/workspace/robust-rail-evaluator/build/TORS" #../../C++/hello"
    Mode: "EVAL_AND_STORE" #EVAL_AND_STORE or EVAL
    PathLocation: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed"
    PathScenario: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed/scenario_evaluator.json"
    PathPlan: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed/plan.json"
    PlanType: "Solver"
    DepartureDelay: "0"
  ConversionAndStorage:  
    PathEvalResult: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed/Evaluation_Results.txt"
    PathScenarioEval: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed"
  DeterministicPlanning:
    LookForSeed: false # looking for a seed, so the seed value is modified, if TestCases is 0 and LookForSeed is true the scenario is not modified only the seed value is modified in the
    DisplaySeed: true
    Seed: 11298