
LocationPath: "/workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/location_solver.json"
ScenarioPath: "/workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/scenario_solver_6.json"
PlanPath: "/workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/scenario_6_plan_5.json"
Mode: "Standard" 
DebugLevel: 2 # 0: none, 1: some, 2: detailed, 3: all
Seed: 70
MaxDuration: 600
TemporaryPlanPath: "//workspace/scenario-planning-inputs/Scenario_settings/Kleine_Binckhorst_landmarks/tmp_plans/scenario_6_plan_5"

TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5

SimulatedAnnealing:
  MaxDuration: 180
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  IntensifyOnImprovement: false
