
LocationPath: "/workspace/scenario-planning-inputs/Location_KleineBinckhorst/location_solver.json"
ScenarioPath: "/workspace/scenario-planning-inputs/Location_KleineBinckhorst/scenarios/scenario_solver_random_distribution2.json"
PlanPath: "/workspace/scenario-planning-inputs/Location_KleineBinckhorst/plans/plan_random_distribution2.json"
Mode: "Standard"
DebugLevel: 0

TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5

SimulatedAnnealing:
  MaxDuration: 3600
  StopWhenFeasible: true
  IterationsUntilReset: 15000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  IntensifyOnImprovement: false
